=== Chamishe/Franot_Encoding_Project_Part2/template_dtd/dtd_template.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT acte (metadatas?, text?)>
    <!ATTLIST acte type (lettre_patente | confirmation | contrat) #IMPLIED>
    <!ELEMENT metadatas (responsabilities?, document?, conservation?)>
        <!ELEMENT responsabilities (transcription*, encoding*)>
            <!ELEMENT transcription (#PCDATA)>
            <!ELEMENT encoding (#PCDATA)>
        <!ELEMENT document (author?, physicalDocument?)>
            <!ELEMENT author (scribe+, sigillant+, tutelage+)>
                <!ELEMENT scribe (#PCDATA)>
                <!ELEMENT sigillant (#PCDATA)>
                <!ELEMENT tutelage (#PCDATA)>
            <!ELEMENT physicalDocument (title+, seal?)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT seal (size*, description+)>
                    <!ATTLIST seal n CDATA #REQUIRED>
                    <!ATTLIST seal statut (attache | detache | disparu) #REQUIRED>
                    <!ATTLIST seal material (cire | plomb) #IMPLIED>
                    <!ELEMENT size (#PCDATA)>
                        <!ATTLIST size type (mm) #REQUIRED>
                    <!ELEMENT description (#PCDATA | caption)*>
                        <!ATTLIST description type (rond | navette | ovale) #IMPLIED>
                        <!ELEMENT caption (#PCDATA | missing | uncertain | abbreviation | name | heraldry)*>
                            <!ELEMENT missing EMPTY>
                            <!ELEMENT uncertain (#PCDATA)>
                            <!ELEMENT abbreviation (#PCDATA | edition)*>
                                <!ELEMENT edition (#PCDATA)>
                            <!ELEMENT name (#PCDATA)>
                            <!ELEMENT heraldry (#PCDATA)>
          <!ELEMENT conservation (institution?, cote?)>
            <!ELEMENT institution (#PCDATA)>
            <!ELEMENT cote (#PCDATA)>
    <!ELEMENT text (subscription?, corroboration?)>
        <!ELEMENT subscription (#PCDATA | name | place | date | abbreviation)*>
            <!ELEMENT place (#PCDATA)>
            <!ELEMENT date (#PCDATA)>
        <!ELEMENT corroboration (#PCDATA | name | place | date | abbreviation)*>

=== Chamishe/Franot_Encoding_Project_Part2/template_dtd/xml_template.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE acte SYSTEM "dtd_template.dtd">

<acte type="lettre_patente">
   <metadatas>
      <responsabilities>
         <transcription>text</transcription>
         <encoding>text</encoding>
      </responsabilities>
      <document>
         <author>
            <scribe>text</scribe>
            <sigillant>text</sigillant>
            <tutelage>text</tutelage>
         </author>
         <physicalDocument>
            <title>text</title>
            <seal n='1' statut="attache" material="cire">
               <size type="mm">text</size>
               <description type="rond"> Description du motif du sceau et si nécessaire de sa 
                  <caption>légende comprenant des <missing/> et des transcriptions 
                     <uncertain>incertaines</uncertain> mais également des 
                     <abbreviation>abréviations contenant une 
                        <edition> édition qui développe de ces dernières</edition>
                     </abbreviation>.Dans cette légende nous trouvons le 
                     <name>nom</name> du sigillant et probablement la description de son 
                     <heraldry>armoirie</heraldry>
                  </caption>
               </description>
            </seal>
         </physicalDocument>
      </document>
      <conservation>
         <institution>text</institution>
         <cote>text</cote>
      </conservation>
   </metadatas>
   <text>
      <subscription>Transcription de la subscription du texte contenant le <name>nom du sigillant et des autres personnes impliquées</name>, les <place>lieux évoqués</place>ainsi qu'une ou plusieurs <date>dates</date> ainsi que des <abbreviation>text avec <edition>text</edition></abbreviation></subscription>
      <corroboration>Transcription comprenant les mêmes informations <name>text</name>, <place>text</place>, <date>text</date></corroboration>
   </text>
</acte>
